version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules  
    command: npm run dev   
    working_dir: /app-backend        
    env_file:
      - ./backend/.env                
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app-frontend:/app-frontend
      - /app-frontend/node_modules    
    working_dir: /app-frontend
    env_file:
      - ./app-frontend/.env.local
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: blog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: blog-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
